order-query:
  external:
    datasource:
      mysql:
        damaohogntu1:
          - username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/test1
            driver-class-name: com.mysql.cj.jdbc.Driver
          - username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/test2
            driver-class-name: com.mysql.cj.jdbc.Driver
        damaohogntu2:
          - username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/test3
            driver-class-name: com.mysql.cj.jdbc.Driver
          - username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/test4
            driver-class-name: com.mysql.cj.jdbc.Driver
      click-house:
        test1:
          url: jdbc:clickhouse://127.0.0.1:3306/test4
          username: root
          password: 123456
      hive:
        test1:
          url: test